
name: csdn

on:
  schedule:
    - cron: "0 0 * * *"
  watch:
    types: [started]
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id  # 自己点的 start,测试完记得注释掉
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests lxml
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: 'run py'
      env:
        COOKIE: ${{ secrets.COOKIE }}  #csdn 请求服务器后返回的，确认身份必备 签到
        LUCKYCOOKIE: ${{ secrets.LUCKLYCOOKIE }}  #csdn 请求服务器后返回的，确认身份必备 抽奖
        USERNAME: ${{ secrets.USERNAME }} # 用户名
        DDSECRET: ${{ secrets.DDSECRET }} # 钉钉机器人加签密钥
        DDPOSTURL: ${{ secrets.DDPOSTURL }} # 钉钉机器人地址

      run: python csdn1.py